// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Athlete struct {
	ID           int64       `json:"id"`
	Firstname    pgtype.Text `json:"firstname"`
	Lastname     pgtype.Text `json:"lastname"`
	ExpiresAt    pgtype.Int8 `json:"expires_at"`
	RefreshToken pgtype.Text `json:"refresh_token"`
	AccessToken  pgtype.Text `json:"access_token"`
}

type Route struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	StartDate    pgtype.Timestamptz `json:"start_date"`
	Name         string             `json:"name"`
	ElapsedTime  int32              `json:"elapsed_time"`
	MovingTime   int32              `json:"moving_time"`
	Distance     float64            `json:"distance"`
	AverageSpeed float64            `json:"average_speed"`
	Elevation    float64            `json:"elevation"`
	Bounds       string             `json:"bounds"`
	SportType    pgtype.Text        `json:"sport_type"`
	Geom         string             `json:"geom"`
}
