// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAthlete = `-- name: GetAthlete :one
SELECT id, firstname, lastname
FROM athlete
WHERE id = $1
`

type GetAthleteRow struct {
	ID        int64       `json:"id"`
	Firstname pgtype.Text `json:"firstname"`
	Lastname  pgtype.Text `json:"lastname"`
}

func (q *Queries) GetAthlete(ctx context.Context, id int64) (GetAthleteRow, error) {
	row := q.db.QueryRow(ctx, getAthlete, id)
	var i GetAthleteRow
	err := row.Scan(&i.ID, &i.Firstname, &i.Lastname)
	return i, err
}

const getAthleteTokens = `-- name: GetAthleteTokens :one
SELECT id, expires_at, refresh_token, access_token
FROM athlete
WHERE id = $1
`

type GetAthleteTokensRow struct {
	ID           int64       `json:"id"`
	ExpiresAt    pgtype.Int8 `json:"expires_at"`
	RefreshToken pgtype.Text `json:"refresh_token"`
	AccessToken  pgtype.Text `json:"access_token"`
}

func (q *Queries) GetAthleteTokens(ctx context.Context, id int64) (GetAthleteTokensRow, error) {
	row := q.db.QueryRow(ctx, getAthleteTokens, id)
	var i GetAthleteTokensRow
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.RefreshToken,
		&i.AccessToken,
	)
	return i, err
}

const getRouteName = `-- name: GetRouteName :one
SELECT name
FROM route
WHERE id = $1 AND user_id = $2
`

type GetRouteNameParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetRouteName(ctx context.Context, arg GetRouteNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getRouteName, arg.ID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getRouteUniqueDistanceMeters = `-- name: GetRouteUniqueDistanceMeters :one
WITH target AS (
    SELECT geom, user_id
    FROM route
    WHERE route.id = $1
      AND geom IS NOT NULL
),
densified AS (
    -- Resample the route to one vertex every 20m for uniform coverage
    SELECT ST_Segmentize(t.geom::geography, 20)::geometry AS dgeom, t.user_id
    FROM target t
),
pts AS (
    SELECT (dp).path[1] AS n, (dp).geom AS pt, d.user_id
    FROM densified d
    CROSS JOIN LATERAL ST_DumpPoints(d.dgeom) dp
),
pt_covered AS (
    -- A point is "covered" if any other route from the same user passes within 10m.
    -- 0.0001 degrees ≈ 11m; using geometry (not geography) keeps the GIST index active.
    SELECT p.n, p.pt,
           EXISTS (
               SELECT 1
               FROM route o
               WHERE o.user_id = p.user_id
                 AND o.id <> $1
                 AND o.geom IS NOT NULL
                 AND ST_DWithin(p.pt, o.geom, 0.0001)
           ) AS covered
    FROM pts p
),
segs AS (
    -- A segment is unique if at least one of its endpoints is not covered
    SELECT ST_MakeLine(a.pt, b.pt) AS seg,
           NOT (a.covered AND b.covered) AS is_unique
    FROM pt_covered a
    JOIN pt_covered b ON b.n = a.n + 1
)
SELECT LEAST(
    COALESCE(SUM(ST_Length(seg::geography)) FILTER (WHERE is_unique), 0),
    (SELECT distance * 1000 FROM route WHERE route.id = $1)
) AS unique_distance_meters
FROM segs
`

// Computes the meters of the route that don't come within 10m of any other route
// from the same user. Uses a point-sampling approach (one point per 20m) with
// geometry ST_DWithin so the GIST spatial index is used for each lookup.
// The result is capped at the route's own Strava-reported distance (in metres)
// so that a fully-unique route can never return a value larger than the route
// itself (PostGIS measures the raw GPS polyline, which is slightly longer than
// Strava's smoothed distance).
func (q *Queries) GetRouteUniqueDistanceMeters(ctx context.Context, id int64) (interface{}, error) {
	row := q.db.QueryRow(ctx, getRouteUniqueDistanceMeters, id)
	var unique_distance_meters interface{}
	err := row.Scan(&unique_distance_meters)
	return unique_distance_meters, err
}

const listAthleteIDs = `-- name: ListAthleteIDs :many
SELECT id
FROM athlete
`

func (q *Queries) ListAthleteIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAthleteIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesByUser = `-- name: ListRoutesByUser :many
SELECT id, user_id, start_date, name, elapsed_time, moving_time, distance, average_speed, elevation, bounds
FROM route
WHERE user_id = $1
ORDER BY start_date DESC
`

type ListRoutesByUserRow struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	StartDate    pgtype.Timestamptz `json:"start_date"`
	Name         string             `json:"name"`
	ElapsedTime  int32              `json:"elapsed_time"`
	MovingTime   int32              `json:"moving_time"`
	Distance     float64            `json:"distance"`
	AverageSpeed float64            `json:"average_speed"`
	Elevation    float64            `json:"elevation"`
	Bounds       string             `json:"bounds"`
}

func (q *Queries) ListRoutesByUser(ctx context.Context, userID int64) ([]ListRoutesByUserRow, error) {
	rows, err := q.db.Query(ctx, listRoutesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoutesByUserRow
	for rows.Next() {
		var i ListRoutesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.Name,
			&i.ElapsedTime,
			&i.MovingTime,
			&i.Distance,
			&i.AverageSpeed,
			&i.Elevation,
			&i.Bounds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeExists = `-- name: RouteExists :one
SELECT COUNT(*) > 0
FROM route
WHERE id = $1
`

func (q *Queries) RouteExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, routeExists, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAthleteTokens = `-- name: UpdateAthleteTokens :exec
UPDATE athlete
SET access_token = $1,
    expires_at   = $2
WHERE id = $3
`

type UpdateAthleteTokensParams struct {
	AccessToken pgtype.Text `json:"access_token"`
	ExpiresAt   pgtype.Int8 `json:"expires_at"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateAthleteTokens(ctx context.Context, arg UpdateAthleteTokensParams) error {
	_, err := q.db.Exec(ctx, updateAthleteTokens, arg.AccessToken, arg.ExpiresAt, arg.ID)
	return err
}

const updateRouteName = `-- name: UpdateRouteName :exec
UPDATE route
SET name = $1
WHERE id = $2 AND user_id = $3
`

type UpdateRouteNameParams struct {
	Name   string `json:"name"`
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) UpdateRouteName(ctx context.Context, arg UpdateRouteNameParams) error {
	_, err := q.db.Exec(ctx, updateRouteName, arg.Name, arg.ID, arg.UserID)
	return err
}

const upsertAthlete = `-- name: UpsertAthlete :exec
INSERT INTO athlete (id, firstname, lastname, access_token, refresh_token, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    firstname     = EXCLUDED.firstname,
    lastname      = EXCLUDED.lastname,
    access_token  = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    expires_at    = EXCLUDED.expires_at
`

type UpsertAthleteParams struct {
	ID           int64       `json:"id"`
	Firstname    pgtype.Text `json:"firstname"`
	Lastname     pgtype.Text `json:"lastname"`
	AccessToken  pgtype.Text `json:"access_token"`
	RefreshToken pgtype.Text `json:"refresh_token"`
	ExpiresAt    pgtype.Int8 `json:"expires_at"`
}

func (q *Queries) UpsertAthlete(ctx context.Context, arg UpsertAthleteParams) error {
	_, err := q.db.Exec(ctx, upsertAthlete,
		arg.ID,
		arg.Firstname,
		arg.Lastname,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	return err
}

const upsertRoute = `-- name: UpsertRoute :exec
INSERT INTO route (id, user_id, start_date, name, elapsed_time, moving_time, distance, average_speed, elevation, bounds, geom)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, ST_GeomFromText($11, 4326))
ON CONFLICT (id) DO UPDATE SET
    user_id       = EXCLUDED.user_id,
    start_date    = EXCLUDED.start_date,
    name          = EXCLUDED.name,
    elapsed_time  = EXCLUDED.elapsed_time,
    moving_time   = EXCLUDED.moving_time,
    distance      = EXCLUDED.distance,
    average_speed = EXCLUDED.average_speed,
    elevation     = EXCLUDED.elevation,
    bounds        = EXCLUDED.bounds,
    geom          = EXCLUDED.geom
`

type UpsertRouteParams struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	StartDate      pgtype.Timestamptz `json:"start_date"`
	Name           string             `json:"name"`
	ElapsedTime    int32              `json:"elapsed_time"`
	MovingTime     int32              `json:"moving_time"`
	Distance       float64            `json:"distance"`
	AverageSpeed   float64            `json:"average_speed"`
	Elevation      float64            `json:"elevation"`
	Bounds         string             `json:"bounds"`
	StGeomfromtext interface{}        `json:"st_geomfromtext"`
}

func (q *Queries) UpsertRoute(ctx context.Context, arg UpsertRouteParams) error {
	_, err := q.db.Exec(ctx, upsertRoute,
		arg.ID,
		arg.UserID,
		arg.StartDate,
		arg.Name,
		arg.ElapsedTime,
		arg.MovingTime,
		arg.Distance,
		arg.AverageSpeed,
		arg.Elevation,
		arg.Bounds,
		arg.StGeomfromtext,
	)
	return err
}
