// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetAthlete(ctx context.Context, id int64) (GetAthleteRow, error)
	GetAthleteTokens(ctx context.Context, id int64) (GetAthleteTokensRow, error)
	GetRouteName(ctx context.Context, arg GetRouteNameParams) (string, error)
	// Computes the meters of the route that don't come within 10m of any other route
	// from the same user. Uses a point-sampling approach (one point per 20m) with
	// geometry ST_DWithin so the GIST spatial index is used for each lookup.
	// The result is capped at the route's own Strava-reported distance (in metres)
	// so that a fully-unique route can never return a value larger than the route
	// itself (PostGIS measures the raw GPS polyline, which is slightly longer than
	// Strava's smoothed distance).
	GetRouteUniqueDistanceMeters(ctx context.Context, id int64) (float64, error)
	ListAthleteIDs(ctx context.Context) ([]int64, error)
	ListRoutesByUser(ctx context.Context, userID int64) ([]ListRoutesByUserRow, error)
	RouteExists(ctx context.Context, id int64) (bool, error)
	UpdateAthleteTokens(ctx context.Context, arg UpdateAthleteTokensParams) error
	UpdateRouteName(ctx context.Context, arg UpdateRouteNameParams) error
	UpsertAthlete(ctx context.Context, arg UpsertAthleteParams) error
	UpsertRoute(ctx context.Context, arg UpsertRouteParams) error
}

var _ Querier = (*Queries)(nil)
